"""remove foreign key subject_code in questions table

Revision ID: ba91599b4171
Revises: 7dfc3d1a7433
Create Date: 2026-07-28 23:25:28.101934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba91599b4171'
down_revision: Union[str, Sequence[str], None] = '7dfc3d1a7433'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'subjects', ['subject_code'], ['subject_code'], onupdate='CASCADE', ondelete='CASCADE')

    # ### end Alembic commands ###
